version: "3.9"

services:
  productos-service:
    build: ./productos_service
    container_name: productos-service
    ports:
      - "8001:8001"

  listas-service:
    build: ./listas_service
    container_name: listas-service
    environment:
      - PRODUCTS_SERVICE_URL=http://productos-service:8001
    ports:
      - "8002:8002"
    depends_on:
      - productos-service
